### ISSUE TITLE
/api/auth/register Error

### ISSUE THREAD

**Issue by privacyosint** [0perationPrivacy/VoIP#1]
I am getting a this error and not sure how to fix it. 

`2021-09-09T21:11:15.897271+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/api/auth/register" host=xxxxx.herokuapp.com request_id=ace4fe65a38f fwd="Ip address" dyno=web.1 connect=0ms service=30001ms status=503 bytes=0 protocol=https`

2021-09-09T21:10:56.993002+00:00 app[web.1]:     at Timeout.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
2021-09-09T21:10:56.993004+00:00 app[web.1]:     at listOnTimeout (internal/timers.js:557:17)
2021-09-09T21:10:56.993004+00:00 app[web.1]:     at processTimers (internal/timers.js:500:7)
2021-09-09T21:10:56.993100+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
2021-09-09T21:10:57.174817+00:00 app[web.1]: (node:22) UnhandledPromiseRejectionWarning: MongooseError: Operation `users.findOne()` buffering timed out after 10000ms

I tried making an account on sign up but nothing loads. I found this early because I checked the website. Can't wait for the show!
How can I fix this?

**Comment by privacyosint** [comment]
Fix is wrong username or password with using mongodb
