### ISSUE TITLE
Can not add API key to new profile

### ISSUE THREAD

**Issue by fightforprivacy** [0perationPrivacy/VoIP#97]
- **Platform:**  Windows 10 v21H1
- **Browser:** Firefox v94.0.2 (64-bit)
- **App Version:** v0.80
- **Provider:** Telnyx
- ### Describe the bug

Unable to save API key from telnyx

**To Reproduce**
1. Unable to send or receive sms or phone calls
2. Delete profile
3. Clear cache and cookies
4. Recreate profile
5. Attempt to save API key
6. Refresh page, see that the API key slot is empty
7. In addition, When API key is entered, unable to retrieve phone numbers

**Expected behavior**
Be able to delete and recreate a profile within the account to send/receive SMS/calls

**Further Information**

When you attempt to add the API key on the front end, the following error displays

```
(node:413) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at exports.checkCallSetting (/root/VoIP/app/controller/fallback.controller.js:312:54)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/VoIP/node_modules/express/lib/router/route.js:137:13)
    at module.exports (/root/VoIP/app/middleware/auth.middleware.js:15:25)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/VoIP/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/VoIP/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at /root/VoIP/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/VoIP/node_modules/express/lib/router/index.js:335:12)
    at next (/root/VoIP/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/VoIP/node_modules/express/lib/router/index.js:174:3)
    at router (/root/VoIP/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/VoIP/node_modules/express/lib/router/index.js:317:13)
    at /root/VoIP/node_modules/express/lib/router/index.js:284:7
(node:413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:413) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

NodeJS version: 10.19.0~dfsg-3ubuntu1

**Comment by fightforprivacy** [comment]
I attempted to start over and update npm, but I get the same error message. 

```
(node:9025) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at exports.checkCallSetting (/root/VoIP/app/controller/fallback.controller.js:312:54)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/VoIP/node_modules/express/lib/router/route.js:137:13)
    at module.exports (/root/VoIP/app/middleware/auth.middleware.js:15:25)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/VoIP/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/VoIP/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at /root/VoIP/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/VoIP/node_modules/express/lib/router/index.js:335:12)
    at next (/root/VoIP/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/VoIP/node_modules/express/lib/router/index.js:174:3)
    at router (/root/VoIP/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/VoIP/node_modules/express/lib/router/index.js:317:13)
    at /root/VoIP/node_modules/express/lib/router/index.js:284:7
(node:9025) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by fightforprivacy** [comment]
After fully deleting the container and starting over, when I go to update the Telnyx API key in the profile, I get the following error in the Console
`this.activeProfile is null`

```
TypeError: this.activeProfile is null
    handleSubmit NumberList.vue:750
    submit NumberList.vue:1
    VueJS 39
        Gt
        n
        _wrapper
        rr
        le
        or
        b
        h
        p
        h
        p
        h
        p
        h
        p
        h
        Kr
        _update
        mount
        get
        mn
        mount
        $mount
        $mount
        init
        h
        h
        p
        h
        Kr
        _update
        mount
        get
        mn
        mount
        $mount
        $mount
        _init
        o
    mountTarget transporter.js:123
    beforeMount transporter.js:89
    VueJS 22
        Gt
        an
        mount
        $mount
        $mount
        init
        h
        h
        Kr
        _update
        mount
        get
        run
        pn
        ae
        Zt
        promise callback*qt
        ae
        update
        update
        notify
        uW
    registerModal modal-manager.js:73
    doShow modal.js:455
    show modal.js:376
    showHandler modal.js:646
    VueJS 2
        Gt
        $emit
    i modal.js:57
    ba events.js:23
    xj modal.js:70
    xj modal.js:103
    VueJS 21
        ma
        h
        l
        Gt
        n
        A
        Kr
        _update
        mount
        get
        run
        pn
        ae
        Zt
        promise callback*qt
        ae
        update
        update
        notify
        set
        set
    enableMenu Setting.vue:130
    click Setting.vue:1
    VueJS 3
        Gt
        n
        _wrapper
vue.esm.js:1906
    VueJS 42
    mountTarget transporter.js:123
    beforeMount transporter.js:89
    VueJS 22
    registerModal modal-manager.js:73
    doShow modal.js:455
    show modal.js:376
    showHandler modal.js:646
    VueJS 2
    i modal.js:57
    (Async: EventListener.handleEvent)
    ba events.js:23
    xj modal.js:70
    xj modal.js:103
    VueJS 21
    enableMenu Setting.vue:130
    click Setting.vue:1
    VueJS 3
```

**Comment by fightforprivacy** [comment]
I have tried v0.80 and v0.79 self hosting and I get the same results

In addition, I get this same error when I attempt to use `https://voip.operationprivacy.com/voip/dashboard` to add a key. More specifically, I get this error

```
TypeError: this.activeProfile is null
    handleSubmit NumberList.vue:742
    submit NumberList.vue:1
    Gt vendor.086226349a000c936715.js:13
    n vendor.086226349a000c936715.js:13
    _wrapper vendor.086226349a000c936715.js:13
    rr vendor.086226349a000c936715.js:13
    le vendor.086226349a000c936715.js:13
    or vendor.086226349a000c936715.js:13
    b vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    p vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    p vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    p vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    p vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    Kr vendor.086226349a000c936715.js:13
    _update vendor.086226349a000c936715.js:13
    mount vendor.086226349a000c936715.js:13
    get vendor.086226349a000c936715.js:13
    mn vendor.086226349a000c936715.js:13
    mount vendor.086226349a000c936715.js:13
    $mount vendor.086226349a000c936715.js:13
    $mount vendor.086226349a000c936715.js:13
    init vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    p vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    Kr vendor.086226349a000c936715.js:13
    _update vendor.086226349a000c936715.js:13
    mount vendor.086226349a000c936715.js:13
    get vendor.086226349a000c936715.js:13
    mn vendor.086226349a000c936715.js:13
    mount vendor.086226349a000c936715.js:13
    $mount vendor.086226349a000c936715.js:13
    $mount vendor.086226349a000c936715.js:13
    _init vendor.086226349a000c936715.js:13
    o vendor.086226349a000c936715.js:13
    mountTarget vendor.086226349a000c936715.js:32
    beforeMount vendor.086226349a000c936715.js:32
    Gt vendor.086226349a000c936715.js:13
    an vendor.086226349a000c936715.js:13
    mount vendor.086226349a000c936715.js:13
    $mount vendor.086226349a000c936715.js:13
    $mount vendor.086226349a000c936715.js:13
    init vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    h vendor.086226349a000c936715.js:13
    Kr vendor.086226349a000c936715.js:13
    _update vendor.086226349a000c936715.js:13
    mount vendor.086226349a000c936715.js:13
    get vendor.086226349a000c936715.js:13
    run vendor.086226349a000c936715.js:13
    pn vendor.086226349a000c936715.js:13
    ae vendor.086226349a000c936715.js:13
    Zt vendor.086226349a000c936715.js:13
vendor.086226349a000c936715.js:13:11705
    Yt https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Wt https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Ut https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Gt https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    n https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    _wrapper https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    (Async: EventListener.handleEvent)
    rr https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    le https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    or https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    b https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    p https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    p https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    p https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    p https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Kr https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    _update https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    get https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mn https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    $mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    $mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    init https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    p https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Kr https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    _update https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    get https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mn https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    $mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    $mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    _init https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    o https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mountTarget https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:32
    beforeMount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:32
    Gt https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    an https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    $mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    $mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    init https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    h https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Kr https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    _update https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    mount https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    get https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    run https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    pn https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    ae https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
    Zt https://voip.operationprivacy.com/static/js/vendor.086226349a000c936715.js:13
```

**Comment by fightforprivacy** [comment]
Just following up on this

When I attempt to add a key, I am getting a 504 error message.. 

![image](https://user-images.githubusercontent.com/92276223/144736669-f91fc6e6-7363-4125-9f04-8921bbf0a55f.png)

**Comment by 0perationPrivacy** [comment]
I tried the above, everything seems to work fine, i tried it on the public hosted site, voip.operationprivacy.com

1. Deleted an existing Telnyx profile from settings
2. Confirmed profile no longer exists in the menu
3. Added a new profile, called it something different
4. Added the telnyx key, hit `get number`, selected the number from the dropdown list
5. Hit `save`
5. The profile dropdown now has the new profile with the number assigned to it.

So not sure what's causing yours to give an error.
You sure the number exists? The API key is correct and not refreshed to a new one? 🧐

**Comment by fightforprivacy** [comment]
> I tried the above, everything seems to work fine, i tried it on the public hosted site, voip.operationprivacy.com
> 
>     1. Deleted an existing Telnyx profile from settings
> 
>     2. Confirmed profile no longer exists in the menu
> 
>     3. Added a new profile, called it something different
> 
>     4. Added the telnyx key, hit `get number`, selected the number from the dropdown list
> 
>     5. Hit `save`
> 
>     6. The profile dropdown now has the new profile with the number assigned to it.
> 
> 
> So not sure what's causing yours to give an error. You sure the number exists? The API key is correct and not refreshed to a new one? 🧐

Yeah, its really odd. 
Now the api key will add and I can generate a number. 

I am wiping my self hosted instance once more, hopefully that will solve it.

**Comment by fightforprivacy** [comment]
Oddly, I keep getting this error after a fresh install
```
a user connected
(node:2719) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at exports.checkCallSetting (/root/VoIP/app/controller/fallback.controller.js:312:54)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/VoIP/node_modules/express/lib/router/route.js:137:13)
    at module.exports (/root/VoIP/app/middleware/auth.middleware.js:15:25)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/VoIP/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/VoIP/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at /root/VoIP/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/VoIP/node_modules/express/lib/router/index.js:335:12)
    at next (/root/VoIP/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/VoIP/node_modules/express/lib/router/index.js:174:3)
    at router (/root/VoIP/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/root/VoIP/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/VoIP/node_modules/express/lib/router/index.js:317:13)
    at /root/VoIP/node_modules/express/lib/router/index.js:284:7
(node:2719) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2719) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 0perationPrivacy** [comment]
currently I don't support troubleshooting containers so I'll have to close this.
